/*
Setup Database
Author: Yuya Jeremy Ong (yjo5006@psu.edu)
*/
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/* Use Provided Database */
USE ds497;

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

/* Define Table Structure */
CREATE TABLE `a2q` (
  `id` int(11) NOT NULL,
  `source` int(11) NOT NULL,
  `target` int(11) NOT NULL,
  `timestamp` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `c2a` (
  `id` int(11) NOT NULL,
  `source` int(11) NOT NULL,
  `target` int(11) NOT NULL,
  `timestamp` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `c2q` (
  `id` int(11) NOT NULL,
  `source` int(11) NOT NULL,
  `target` int(11) NOT NULL,
  `timestamp` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/* Initialize Primary Keys */
ALTER TABLE `a2q`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `c2a`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `c2q`
  ADD PRIMARY KEY (`id`);

/* Auto Increment IDs */
ALTER TABLE `a2q`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `c2a`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `c2q`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
